[package]
name = "rim-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
argon2 = "0.6.0"
base64 = "0.23.1"
chacha20poly1305 = "0.11.0"
futures = "0.3.34"
hex = "0.4.3"
libp2p = { version = "0.56", features = ["tokio", "tcp", "quic", "noise", "yamux", "mdns", "request-response", "json", "macros", "identify", "ed25519"] }
rand = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
thiserror = "2.0.21"
time = { version = "0.3.55", features = ["formatting", "local-offset"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.44"
vodozemac = "0.11"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_Power"] }
